# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YSHistogramView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YSHistogram'

  # Pods for YSHistogramView

  target 'YSHistogramViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YSHistogramViewUITests' do
    # Pods for testing
  end

end
